apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nad-ipvlan-ens3
  namespace: default
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "ipvlan",
            "mode": "l2",
            "master": "ens3",
            "ipam": {
                "type": "static"
            }
      }'
