apiVersion: v1
kind: Pod
metadata:
  name: dnsutils-kubemaster-2
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "nad-ipvlan-ens3",
          "namespace": "default",
          "ips": ["172.16.10.131/24"]
        }
      ]
spec:
  containers:
  - name: dnsutils-kubemaster
    image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always  
  nodeName: kubemaster
  dnsPolicy: ClusterFirst
