apiVersion: v1
kind: Pod
metadata:
  name: busybox-kubemaster2
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "nad-bridge-cni0",
          "namespace": "default",
          "ips": ["172.16.10.140/24"]
        }
      ]
spec:
  containers:
  - name: busybox-kubemaster
    image: busybox
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always  
  nodeName: kubemaster
  dnsPolicy: ClusterFirst
