apiVersion: v1
kind: Pod
metadata:
  name: busybox-kubenode1
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "nad-host-device-ens3",
          "namespace": "default"
        }
      ]
spec:
  containers:
  - name: busybox-kubemaster
    image: busybox
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always  
  nodeName: kubenode1
  dnsPolicy: ClusterFirst
